#Configuration
VERBOSE: False
MODEL:
#  MODE: 'DeFlare'
#  ARCH: 'ConvIR'
#  ARGS:
#    version: 'base'
#    data: 'ITS'
#    base_channel: 32
  MODE: 'DeFlare'
  ARCH: 'UBlock'
  ARGS:
    in_channels: 3
    base_channels: 20

# Optimization arguments.
TRAINOPTIM:
  BATCH: 4 # origin: 2
  EPOCHS: 300
  DEVICES: 1
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4 #origin: 2e-4
  LR_MIN: 1e-6 # origin: 1e-6
  # BETA1: 0.9
DATASET:
  LENGTH: 32 # origin: 8192
  MODE: 'Flare7Kpp'  # 'local','Flare7K','Flare7Kpp'
  LOCAL_DIR: './dataset/flare7k_local' # path to local dataset
  BACKGROUND_DIR: './dataset/Flickr24K' # path to background image
  FLARE7KPP_DIR: './dataset/Flare7Kpp' # path to flare7kpp dataset
  REAL_PROPORTION: 0.5 # proportion of real images in the dataset
  REFLECTIVE_PROPORTION: 1.0 # proportion of reflective images in the dataset
TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256 # origin: 256
  VAL_PS: 512
  TRAIN_DIR: './dataset/flare7k_local'       # path to local
  LOSS:
    L1CharbonnierLoss:
      eps: !!float 1e-6
      loss_weight: 1.0
    FocalFrequencyLoss:
      alpha: 1.0
      loss_weight: 1.5
    SSIMLoss:
      loss_weight: 1.0
#    ColorConsistencyLoss:
#      loss_weight: !!float 1e-4
    LPIPSLoss:
      net: 'vgg'
      loss_weight: 0.02

  VAL:
    REAL_DIR: './dataset/Flare7Kpp/test_data/real'
    REAL_SAVE: './val_result_real'
    SYN_DIR: './dataset/Flare7Kpp/test_data/synthetic'
    SYN_SAVE: './val_result_syn'
  SAVE_DIR: './checkpoints'           # path to save models and images
  SAVE_AFTER_EVERY: 5
TESTING:
  TEST_PS: None
  TEST_DIR_REAL: './dataset/Flare7Kpp/test_data/real' # path to validation data
  TEST_DIR_SYN: './dataset/Flare7Kpp/test_data/synthetic' # path to validation data
